In [1]:
install.packages("ggplot2")

Warning message:
"dependencies 'MASS', 'lattice' are not available"also installing the dependencies 'colorspace', 'utf8', 'nlme', 'Matrix', 'farver', 'labeling', 'munsell', 'R6', 'RColorBrewer', 'viridisLite', 'fansi', 'magrittr', 'pillar', 'pkgconfig', 'cli', 'glue', 'gtable', 'isoband', 'lifecycle', 'mgcv', 'rlang', 'scales', 'tibble', 'vctrs', 'withr'




  There are binary versions available but the source versions are later:
              binary  source needs_compilation
colorspace     2.0-1   2.1-0              TRUE
utf8           1.2.1   1.2.4              TRUE
nlme         3.1-152 3.1-164              TRUE
Matrix         1.3-3   1.6-5              TRUE
farver         2.1.0   2.1.1              TRUE
labeling       0.4.2   0.4.3             FALSE
R6             2.5.0   2.5.1             FALSE
RColorBrewer   1.1-2   1.1-3             FALSE
viridisLite    0.4.0   0.4.2             FALSE
fansi          0.4.2   1.0.6              TRUE
magrittr       2.0.1   2.0.3              TRUE
pillar         1.6.0   1.9.0             FALSE
cli            2.5.0   3.6.2              TRUE
glue           1.4.2   1.7.0              TRUE
gtable         0.3.0   0.3.4             FALSE
isoband        0.2.4   0.2.7              TRUE
lifecycle      1.0.0   1.0.4             FALSE
mgcv          1.8-35   1.9-1              TRUE
rlang         0.4.11   1.1.3     

installing the source packages 'labeling', 'R6', 'RColorBrewer', 'viridisLite', 'pillar', 'gtable', 'lifecycle', 'withr', 'ggplot2'

Warning message in install.packages("ggplot2"):
"installation of package 'lifecycle' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'pillar' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'gtable' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'ggplot2' had non-zero exit status"

In [1]:
1

[1] 1

In [2]:
1+1

[1] 2

In [3]:
a <- 1

In [4]:
b = 1

In [5]:
a == b

[1] TRUE

In [6]:
class(a)

[1] "numeric"

In [7]:
class(b)

[1] "numeric"

In [8]:
paste("Mostrar valor")

[1] "Mostrar valor"

In [9]:
print(a)

[1] 1


In [10]:
paste(a)

[1] "1"

In [11]:
msg <- "hola"
msg

[1] "hola"

In [12]:
5*3

[1] 15

In [13]:
10/2

[1] 5

In [14]:
x = c(0.5, 0.6)       ## numeric
x = c(TRUE, FALSE)    ## Logical
x = c(T,F)            ## Logical
x = c("a", "b", "c")  ## character
x = 9:29              ## integer
x = c(1+0i, 2+4i)     ## complex

In [15]:
x

[1] 1+0i 2+4i

In [16]:
class(x)

[1] "complex"

In [17]:
x = vector("numeric" , length = 10)
x

[1] 0 0 0 0 0 0 0 0 0 0

In [18]:
y = c(1.7, "a") ## character
y

[1] "1.7" "a"

In [19]:
class(y)

[1] "character"

In [20]:
y = c(TRUE, 2)     ## numeric
paste("valor de y :")
y
paste("Clase de y :")
class(y)

[1] "valor de y :"

[1] 1 2

[1] "Clase de y :"

[1] "numeric"

In [21]:
m = matrix(nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [22]:
dim(m)

[1] 2 3

In [23]:
m = matrix(1:6, nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [24]:
x = 1:3
y = 1:12
cbind (x, y)

x y 
 [1,] 1  1
 [2,] 2  2
 [3,] 3  3
 [4,] 1  4
 [5,] 2  5
 [6,] 3  6
 [7,] 1  7
 [8,] 2  8
 [9,] 3  9
[10,] 1 10
[11,] 2 11
[12,] 3 12

In [25]:
rbind(x,y)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
x 1    2    3    1    2    3    1    2    3     1     2     3   
y 1    2    3    4    5    6    7    8    9    10    11    12

In [26]:
x = list(1, "a", TRUE, 1 + 4i)
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

In [27]:
x = factor(c( 'yes', 'yes', 'no', 'yes', 'no'))
x

[1] yes yes no  yes no 
Levels: no yes

In [28]:
## Crea un vector con valores NA
x = c(1, 2, NA, 10, 3)
## Devuelve un vector lógico idicando que elementos son NA 
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [29]:
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [30]:
class(iris)

[1] "data.frame"

In [31]:
?iris

iris                 package:datasets                  R Documentation

_E_d_g_a_r _A_n_d_e_r_s_o_n'_s _I_r_i_s _D_a_t_a

_D_e_s_c_r_i_p_t_i_o_n:

     This famous (Fisher's or Anderson's) iris data set gives the
     measurements in centimeters of the variables sepal length and
     width and petal length and width, respectively, for 50 flowers
     from each of 3 species of iris.  The species are _Iris setosa_,
     _versicolor_, and _virginica_.

_U_s_a_g_e:

     iris
     iris3
     
_F_o_r_m_a_t:

     'iris' is a data frame with 150 cases (rows) and 5 variables
     (columns) named 'Sepal.Length', 'Sepal.Width', 'Petal.Length',
     'Petal.Width', and 'Species'.

     'iris3' gives the same data arranged as a 3-dimensional array of
     size 50 by 4 by 3, as represented by S-PLUS.  The first dimension
     gives the case number within the species subsample, the second the
     measurements with names 'Sepal L.', 'Sepal W.', 'Petal L.', and
     'Petal W.', and the third the species.

_S_o_u_r_c_e:

     Fisher, R. A. (1936) The use of multiple measurements in taxonomic
     problems.  _Annals of Eugenics_, *7*, Part II, 179-188.

     The data were collected by Anderson, Edgar (1935).  The irises of
     the Gaspe Peninsula, _Bulletin of the American Iris Society_,
     *59*, 2-5.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole. (has 'iris3' as 'iris'.)

_S_e_e _A_l_s_o:

     'matplot' some examples of which use 'iris'.

_E_x_a_m_p_l_e_s:

     dni3 <- dimnames(iris3)
     ii <- data.frame(matrix(aperm(iris3, c(1,3,2)), ncol = 4,
                             dimnames = list(NULL, sub(" L.",".Length",
                                             sub(" W.",".Width", dni3[[2]])))),
         Species = gl(3, 50, labels = sub("S", "s", sub("V", "v", dni3[[3]]))))
     all.equal(ii, iris) # TRUE

install.packages("tidyverse")

### Profe a mi no me funciono usar el install.packages(), lo instale directamente desde el anaconda prompt con esto: conda install -c r r-tidyverse

In [36]:
library(tidyverse)

Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Registered S3 method overwritten by 'rvest':
  method            from
  read_xml.response xml2
-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
v ggplot2 3.1.1       v purrr   0.3.2  
v tibble  2.1.1       v dplyr   0.8.0.1
v tidyr   0.8.3       v stringr 1.4.0  
v readr   1.3.1       v forcats 0.4.0  
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()


# Hola

## Hola

Hola

In [38]:
data(mpg)
mpg

manufacturer model              displ year cyl trans      drv cty hwy fl 
1   audi         a4                 1.8   1999 4   auto(l5)   f   18  29  p  
2   audi         a4                 1.8   1999 4   manual(m5) f   21  29  p  
3   audi         a4                 2.0   2008 4   manual(m6) f   20  31  p  
4   audi         a4                 2.0   2008 4   auto(av)   f   21  30  p  
5   audi         a4                 2.8   1999 6   auto(l5)   f   16  26  p  
6   audi         a4                 2.8   1999 6   manual(m5) f   18  26  p  
7   audi         a4                 3.1   2008 6   auto(av)   f   18  27  p  
8   audi         a4 quattro         1.8   1999 4   manual(m5) 4   18  26  p  
9   audi         a4 quattro         1.8   1999 4   auto(l5)   4   16  25  p  
10  audi         a4 quattro         2.0   2008 4   manual(m6) 4   20  28  p  
11  audi         a4 quattro         2.0   2008 4   auto(s6)   4   19  27  p  
12  audi         a4 quattro         2.8   1999 6   auto(l5)   4   15  25  p  
13  audi         a4 quattro         2.8   1999 6   manual(m5) 4   17  25  p  
14  audi         a4 quattro         3.1   2008 6   auto(s6)   4   17  25  p  
15  audi         a4 quattro         3.1   2008 6   manual(m6) 4   15  25  p  
16  audi         a6 quattro         2.8   1999 6   auto(l5)   4   15  24  p  
17  audi         a6 quattro         3.1   2008 6   auto(s6)   4   17  25  p  
18  audi         a6 quattro         4.2   2008 8   auto(s6)   4   16  23  p  
19  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   14  20  r  
20  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   11  15  e  
21  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   14  20  r  
22  chevrolet    c1500 suburban 2wd 5.7   1999 8   auto(l4)   r   13  17  r  
23  chevrolet    c1500 suburban 2wd 6.0   2008 8   auto(l4)   r   12  17  r  
24  chevrolet    corvette           5.7   1999 8   manual(m6) r   16  26  p  
25  chevrolet    corvette           5.7   1999 8   auto(l4)   r   15  23  p  
26  chevrolet    corvette           6.2   2008 8   manual(m6) r   16  26  p  
27  chevrolet    corvette           6.2   2008 8   auto(s6)   r   15  25  p  
28  chevrolet    corvette           7.0   2008 8   manual(m6) r   15  24  p  
29  chevrolet    k1500 tahoe 4wd    5.3   2008 8   auto(l4)   4   14  19  r  
30  chevrolet    k1500 tahoe 4wd    5.3   2008 8   auto(l4)   4   11  14  e  
... ...          ...                ...   ...  ... ...        ... ... ... ...
205 toyota       toyota tacoma 4wd  3.4   1999 6   auto(l4)   4   15  19  r  
206 toyota       toyota tacoma 4wd  4.0   2008 6   manual(m6) 4   15  18  r  
207 toyota       toyota tacoma 4wd  4.0   2008 6   auto(l5)   4   16  20  r  
208 volkswagen   gti                2.0   1999 4   manual(m5) f   21  29  r  
209 volkswagen   gti                2.0   1999 4   auto(l4)   f   19  26  r  
210 volkswagen   gti                2.0   2008 4   manual(m6) f   21  29  p  
211 volkswagen   gti                2.0   2008 4   auto(s6)   f   22  29  p  
212 volkswagen   gti                2.8   1999 6   manual(m5) f   17  24  r  
213 volkswagen   jetta              1.9   1999 4   manual(m5) f   33  44  d  
214 volkswagen   jetta              2.0   1999 4   manual(m5) f   21  29  r  
215 volkswagen   jetta              2.0   1999 4   auto(l4)   f   19  26  r  
216 volkswagen   jetta              2.0   2008 4   auto(s6)   f   22  29  p  
217 volkswagen   jetta              2.0   2008 4   manual(m6) f   21  29  p  
218 volkswagen   jetta              2.5   2008 5   auto(s6)   f   21  29  r  
219 volkswagen   jetta              2.5   2008 5   manual(m5) f   21  29  r  
220 volkswagen   jetta              2.8   1999 6   auto(l4)   f   16  23  r  
221 volkswagen   jetta              2.8   1999 6   manual(m5) f   17  24  r  
222 volkswagen   new beetle         1.9   1999 4   manual(m5) f   35  44  d  
223 volkswagen   new beetle         1.9   1999 4   auto(l4)   f   29  41  d  
224 volkswagen   new beetl